---
title: "SVD"
author: "Chengyu Du"
date: "2023-11-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(Rcpp)
library(RcppArmadillo)
```

```{r}
Rcpp::sourceCpp('/Users/duchengyu/Documents/GitHub/Spatial-Constrained-Matrix-Decomposition/Code/svd.cpp')
```

```{r}
# Example usage in R:
set.seed(432)
X <- matrix(rnorm(100), 100, 10)
U <- matrix(rnorm(100), 100, 10)
Sigma <- diag(rnorm(10))
V <- matrix(rnorm(100), 10, 10)
D <- matrix(replace(diag(10), TRUE, 1), 10, 100)
result <- gradient_descent_svd(X, U, Sigma, V, D, lambda = 1, alpha = 1e-6, tol = 1e-10, max_iter = 1000)
U_updated <- result$U
Sigma_updated <- result$Sigma
V_updated <- result$V
```



```{r include=FALSE}
library(hdf5r)
library(tidyverse)
library(Seurat)
library(Matrix)
library(scales)
library(cowplot)
library(RCurl)
library(ggplot2)
library(dplyr)
```



```{r include=FALSE}

# Load the data
adata <- Read10X_h5("/Users/duchengyu/Desktop/SpaGCN/tutorial/data/151673/expression_matrix.h5")

# Create Seurat object
adata <- CreateSeuratObject(counts = adata)

# Load spatial data
spatial <- read.csv("/Users/duchengyu/Desktop/SpaGCN/tutorial/data/151673/positions.txt", header = FALSE, sep = ",", row.names = 1)

# Add spatial data to Seurat object
adata[["x1"]] <- spatial[[1]]
adata[["x2"]] <- spatial[[2]]
adata[["x3"]] <- spatial[[3]]
adata[["x4"]] <- spatial[[4]]
adata[["x5"]] <- spatial[[5]]
adata[["x_array"]] <- spatial[[2]]
adata[["y_array"]] <- spatial[[3]]
adata[["x_pixel"]] <- spatial[[4]]
adata[["y_pixel"]] <- spatial[[5]]

# Select captured samples
adata <- subset(adata, subset = x1 == 1)

# Convert gene names to uppercase
rownames(adata) <- toupper(rownames(adata))


```

```{r}
# Access the raw counts matrix
raw_counts_matrix <- adata@assays$RNA@counts
```


```{r}
# If you have normalized or transformed the data, access the data matrix
X <- t(adata@assays$RNA@data)
```

```{r include=FALSE}
result <- mySVD(X,10)
```

```{r}
U <- result$U  
s <- result$s  
V <- result$V  
```


```{r}
X_matrix <- as.matrix(X)
```

```{r}
s = as.vector(s)
```

```{r}
Sigma <- diag(s)
```

```{r}

D <- matrix(0, nrow = 10, ncol = 3639)


for (i in 1:10) {
  D[i, i] <- 1
  if (i == 3639) {
    D[i, 1] <- -1
  } else {
    D[i, i + 1] <- -1
  }
}

```

```{r}
calculate_regularization(X_matrix,V,D)
```


```{r}
Fn <- norm(X - U %*% Sigma %*% t(V), type = "F")
```

```{r}
Fn
```

```{r}
c <- solve(Sigma)
```




```{r}
Opti_result <- gradient_descent_svd(X_matrix, U, Sigma, V, D, lambda = 0.001, alpha = 1e-10, tol = 1e-4, max_iter = 100)
U_updated <- Opti_result$U
V_updated <- Opti_result$V
```







